import { Footer } from "@/components/shared/Footer";
import React from "react";

const Terms = () => {
  return (
    <div className="min-h-screen  text-gray-300 flex flex-col">
      <div className="flex-1">
        <div className="max-w-4xl mx-auto px-4 py-16">
          <div className=" border border-[#333] rounded-2xl p-6 md:p-10 mb-16">
            <h1 className="text-3xl md:text-4xl font-bold mb-8 text-center bg-clip-text text-transparent bg-gradient-to-r from-[#00F0FF] to-[#FF2E9F]">
              Terms and Conditions
            </h1>

            <div className="space-y-10">
              <Section
                title="Agreement to Terms"
                content={
                  <p>
                    These Terms of Service (the Terms) are a legal agreement
                    between you and Cricon AI, and they govern your use of the
                    criconai.com website and services (collectively, the
                    Service). By accessing or using the Service, you agree to be
                    bound by these Terms and by the Cricon AI Privacy Policy,
                    which is incorporated into these Terms by reference. If you
                    do not agree to these Terms, you may not use the Service.
                  </p>
                }
              />

              <Section
                title="Disclaimer"
                content={
                  <p>
                    The Service is provided on an as is and as available basis.
                    Cricon AI does not warrant that the Service will be
                    error-free, uninterrupted, or secure, and you use the
                    Service at your own risk. Cricon AI is not responsible for
                    any legal issues arising from content generated by AI.
                  </p>
                }
              />

              <Section
                title="Refunds and Cancellations"
                content={
                  <p>
                    All purchases are final. We do not currently offer refunds
                    for any services or credits purchased. This policy may be
                    reviewed and updated in the future, and any changes will be
                    communicated through our website.
                  </p>
                }
              />

              <Section
                title="User Accounts"
                content={
                  <p>
                    To access certain features of the Service, you must create
                    an account. You are responsible for maintaining the
                    confidentiality of your account credentials and for all
                    activities that occur under your account. You agree to
                    provide accurate and complete information during
                    registration and to keep this information up to date.
                  </p>
                }
              />

              <Section
                title="Intellectual Property"
                content={
                  <p>
                    All content on the Service, including text, graphics, logos,
                    and software, is the property of Cricon AI or its licensors
                    and is protected by intellectual property laws. You are
                    granted a limited, non-exclusive, non-transferable license
                    to access and use the Service for your personal or business
                    purposes.
                  </p>
                }
              />

              <Section
                title="User Content"
                content={
                  <p>
                    You retain ownership of any content you submit through the
                    Service. By using our Service, you grant Cricon AI a
                    worldwide, non-exclusive, royalty-free license to use,
                    reproduce, modify, and display your content solely for the
                    purpose of providing and improving our services.
                  </p>
                }
              />

              <Section
                title="Prohibited Activities"
                content={
                  <p>
                    You agree not to use the Service for any illegal purpose or
                    in violation of any laws. Prohibited activities include:
                    attempting to gain unauthorized access to our systems,
                    interfering with other users enjoyment of the Service, or
                    using the Service to generate harmful, abusive, or illegal
                    content.
                  </p>
                }
              />

              <Section
                title="Limitation of Liability"
                content={
                  <p>
                    To the maximum extent permitted by law, Cricon AI shall not
                    be liable for any indirect, incidental, special,
                    consequential, or punitive damages, or any loss of profits
                    or revenues, whether incurred directly or indirectly, or any
                    loss of data, use, goodwill, or other intangible losses
                    resulting from your use of the Service.
                  </p>
                }
              />

              <Section
                title="Changes to Terms"
                content={
                  <p>
                    We may update these Terms from time to time. The most
                    current version will always be posted on our website. By
                    continuing to access or use the Service after revisions
                    become effective, you agree to be bound by the revised
                    terms.
                  </p>
                }
              />

              <Section
                title="Contact Us"
                content={
                  <p>
                    If you have any questions about these Terms and Conditions,
                    please contact us at:
                    <br />
                    <span className="text-[#00F0FF]">support@criconai.com</span>
                  </p>
                }
              />
            </div>
          </div>
        </div>
      </div>
      <Footer />
    </div>
  );
};

// Reusable Section Component
const Section = ({
  title,
  content,
}: {
  title: string;
  content: React.ReactNode;
}) => (
  <div className="border-b border-[#333] pb-8 last:border-0 last:pb-0">
    <h2 className="text-2xl font-bold mb-5 bg-clip-text text-transparent bg-gradient-to-r from-[#00F0FF] to-[#B026FF]">
      {title}
    </h2>
    <div className="text-gray-300">{content}</div>
  </div>
);

export default Terms;
